/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PointerArray.h"
#include "PluginProcessor.h"

class Parameters;
class InterfaceComponent;

//==============================================================================
/**
*/
class SquarAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    SquarAudioProcessorEditor (SquarAudioProcessor* ownerFilter);
    ~SquarAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
	
	void configureParameters(Parameters *parameters);
	void appendComponent(InterfaceComponent *component, String id, bool visible, int x, int y, int width, int height);

private:
	OwnedPointerArray<InterfaceComponent> controls;
	//OwnedPointerArray<SequencerChannelControl> sequencerChannels;

    SquarAudioProcessor* getProcessor() const
    {
        return static_cast <SquarAudioProcessor*> (getAudioProcessor());
    }
};


#endif  // PLUGINEDITOR_H_INCLUDED
